wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717265869
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 105
      3:
      - 23
      4: 3.10.0
      5: 0.17.0
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
pretrained_model_name_or_path:
  desc: null
  value: yisol/IDM-VTON
width:
  desc: null
  value: 384
height:
  desc: null
  value: 512
num_inference_steps:
  desc: null
  value: 30
output_dir:
  desc: null
  value: result
data_dir:
  desc: null
  value: /notebooks/ayna/working_repo/IDM-VTON/dataset/deepfashion_dataset
seed:
  desc: null
  value: 42
batch_size:
  desc: null
  value: 24
num_epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
save_interval:
  desc: null
  value: 50
guidance_scale:
  desc: null
  value: 2.0
mixed_precision:
  desc: null
  value: null
enable_xformers_memory_efficient_attention:
  desc: null
  value: false
